### ISSUE TITLE
Just wanted to spend a moment to say thanks.

### ISSUE THREAD

**Issue by Laxystem** [urosjarc/db-messiah#1]
All existing Kotlin SQL libraries are either actually Java libraries, or use implicit scope magic.

Thank you very much for implementing this library - finally something different that actually uses Kotlin's features! This will (hopefully) make development of my own project much easier.

**Comment by urosjarc** [comment]
@Laxystem If you like we can jump on a zoom call I would love to hear what specific needs you have and to provide assistance... Please message me over public email... jar.fmf@gmail.com :)
